MyInstagram/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyInstagram.Models;
using MyInstagram.ViewModels;

namespace MyInstagram.Controllers
{
    public class CommentController : Controller
    {
        private ApplicationContext _context;

        public CommentController(ApplicationContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> Add(string publicationId, string userId,  string commentMessage)
        {
            Comment comment = new Comment
            {
                CommentMessage = commentMessage,
                Date = DateTime.Now,
                PublicationId = publicationId,
                UserId = userId,
                UserName = User.Identity.Name
            };
            await _context.Comments.AddAsync(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MyInstagram/Controllers/LikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyInstagram.Models;
using MyInstagram.ViewModels;

namespace MyInstagram.Controllers
{
    public class LikeController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly UserManager<User> _userManager;

        public LikeController(ApplicationContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddLikeViewModel model)
        {
            User user = await _userManager.FindByNameAsync(User.Identity.Name);
            Like like = new Like
            {
                UserId = model.UserId,
                PublicationId = model.PublicationId
            };
            if (_context.Likes.Any(l => l.UserId == user.Id && l.PublicationId == model.PublicationId))
            {
                return RedirectToAction("Delete", like);
            }

            if (ModelState.IsValid)
            {
               await _context.Likes.AddAsync(like);
               await _context.SaveChangesAsync();
            }

            return RedirectToAction("Counter", new {postId = like.PublicationId});
        }

        public async Task<IActionResult> Delete(Like like)
        {
            var result = await _context.Likes.
                FirstAsync(l => l.UserId == like.UserId && l.PublicationId == like.PublicationId);
            if (result != null)
            {
                _context.Likes.Remove(result);
                await _context.SaveChangesAsync();
            }
            
            return RedirectToAction("Counter", new { postId = like.PublicationId });
        }

        public IActionResult Counter(string postid)
        {
            var count = _context.Likes.Where(l => l.PublicationId == postid).ToList();
            return Json(count.Count);
        }
    }
}

MyInstagram/Views/Shared/PartialViews/CommentPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.Localization
@model MyInstagram.ViewModels.CommentViewModel
@inject UserManager<User> UserManager
@inject ApplicationContext Context
@inject IViewLocalizer Localizer;
@{
    var user = await UserManager.FindByNameAsync(User.Identity.Name);
}

<div class="form-group col-lg-12">
    <input class="form-control border-0" id="postText-@Model.PublicationId" placeholder=@Localizer["CommentPlaceholder"] />
    <button class="btn btn-outline-dark" type="button" 
            onclick="addComment('@Model.PublicationId', '@user.Id')">@Localizer["AddComment"]</button>
</div>
<div class="col-lg-12">
    <h6 id="app-@Model.PublicationId">@Localizer["Comments"]</h6>
    @{
        List<Comment> comments = Context.Comments.Where(c => c.PublicationId == @Model.PublicationId).ToList();
        foreach (var comment in comments.TakeLast(3).OrderByDescending(c => c.Date))
        {
            <span ></span>
            <p > <span class="font-weight-bold">@comment.UserName</span> : @comment.CommentMessage</p>
        }
    }
</div>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    function addComment(publicationId, userId) {
        $.ajax({
            url: '@Url.Action("Add", "Comment")',
            method: 'POST',
            data: {
                'publicationId': publicationId,
                'userId': userId,
                'commentMessage': $('#postText-' + publicationId).val()
            },
            success: function () {
                $('#app-' + publicationId).
                append('<p>' 
                + '<span class="font-weight-bold">@User.Identity.Name</span> : ' 
                + $('#postText-' + publicationId).val() + '</p>');
                $('#postText-' + publicationId).val(null);
            }
            }
        );
    };
</script>

MyInstagram/Views/Shared/PartialViews/LikePartial.cshtml
@using Microsoft.AspNetCore.Identity;
@model MyInstagram.ViewModels.AddLikeViewModel
@inject UserManager<User> UserManager
@inject ApplicationContext Context
@{
    var user = await @UserManager.FindByNameAsync(User.Identity.Name);
}

@if (User.Identity.IsAuthenticated)
{ <form>
    <button class="btn btn-link table-hover"
            type="button"
            onclick="sendLike('@Model.PublicationId', '@user.Id')"
            id="@Model.Id">
        ❤
    </button>
</form>
}
<span id="@Model.PublicationId">
</span>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    $(function(){
        $('#@Model.PublicationId')
        .load('@Url.Action("Counter", "Like", new { postId = @Model.PublicationId })');
    });

    function sendLike(publicationId, userId) {
        $.ajax({
                url: '@Url.Action("Add", "Like")',
                method: 'POST',
                data: {
                    'publicationId': publicationId,
                    'userId': userId
                },
            success: function (data) {
                $('#'+publicationId).text(data);
            }
            }
        );
    };
</script>

MyInstagram/Views/Shared/PartialViews/UserSearchResult.cshtml
@model List<User>
<div id="searchresults" class="d-flex flex-column w-100">
    @if (@Model.Count > 0)
    {
        foreach (var user in Model)
        {
            <div class=" py-2">
                <img width="50" height="50" class="rounded-circle" src="~/@user.AvatarImagePath" /> 
                <a class="col-lg-4" asp-action="Details" asp-controller="User" 
                   asp-route-userId="@user.Id">@user.UserName</a>
            </div>
        }
    }
</div>

MyInstagram/Views/Shared/PartialViews/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
 
@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions
 
@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}
 
<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
      asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString"
      method="post" class="form-horizontal">
    @Localizer["Language:"] <select name="culture" onchange="this.form.submit();"
                                    asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                    asp-items="cultureItems"
                                    ></select>
</form>